# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

######## Ubuntu boilerplate ########

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# Source PATH config (login shells get this via bash_profile,
# but non-login interactive shells — i.e. normal terminal windows — do not)
[[ -f $HOME/.path ]] && source $HOME/.path

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

######## Color settings ########
# Detect terminal color support
# color_prompt=256 if 256-color, color_prompt=yes if basic color, unset if none
color_prompt=
if [ -x /usr/bin/tput ] && tput setaf 1 &>/dev/null; then
    ncolors=$(tput colors 2>/dev/null)
    if [ "${ncolors:-0}" -ge 256 ] 2>/dev/null; then
        color_prompt=256
    elif [ "${ncolors:-0}" -ge 8 ] 2>/dev/null; then
        color_prompt=yes
    fi
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

######## Aliases ########

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    #alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# 
alias od="od -A x -t x1"
alias src='[[ -f $HOME/.profile ]] && source $HOME/.profile; [[ -f $HOME/.bashrc ]] && source $HOME/.bashrc'
alias ls="ls -CF --color"

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# If there are additional aliases in ~/.bash_aliases, source them
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

######## Changes to PATH ########
# Changes in PATH have been moved to ~/.profile

######## Extra logic to help PS1 not overwrite venv ########
export VIRTUAL_ENV_DISABLE_PROMPT=1

# Print " (venvname)" if a virtualenv is active
_venv_ps1() {
    if [ -n "$VIRTUAL_ENV" ]; then
        printf " (%s)" "${VIRTUAL_ENV##*/}"
    fi
}

######## PS1, Colored command line based on hostname/username ########
[[ -f $HOME/.bash_utils ]] && source $HOME/.bash_utils
# RESET sets 0m, which resets the changes so far
RESET='\[$(tput sgr0)\]'
# 1 is bold
# 38;5 means next input sets foreground color
# \e is escape character, ake \033
export PS1="\n[ \[\e[1;38;5;$(_color_whoami)m\]\u${RESET}\[\e[1m\]@\[\e[38;5;$(_color_hostname)m\]\h${RESET}\[\e[1m\]:\[\e[38;5;$(_color_pwd)m\]\w${RESET}\$( _venv_ps1 ) ]\n\\$ "

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

#export GTK2_RC_FILES="$HOME/.config/gtk-3.0/settings.ini"
#export GTK_THEME=Adwaita:dark

######## Changed/additional commands ########

# Swaylock with custom background if it exists
if [[ -f "$HOME/Pictures/GraveArtoriasFinalWP.png" ]]
then
    alias swaylock="swaylock -i $HOME/Pictures/GraveArtoriasFinalWP.png"
fi


# Print top n (default 1) files in downloads
if [[ -d "$HOME/Downloads" ]]
then
    alias down="echo '$HOME/Downloads/$(ls -t  $HOME/Downloads | head -n 1)'"
fi


######## PulseAudio stuff ########
# Help from https://unix.stackexchange.com/questions/132230/read-out-pulseaudio-volume-from-commandline-i-want-pactl-get-sink-volume#164740
getdefaultsinkname() {
    pacmd stat | awk -F": " '/^Default sink name: /{printf $2}'
}
getdefaultsinkvol() {
    pacmd list-sinks | awk '/^\s+name: /{indefault = $2 == "<'$(getdefaultsinkname)'>"} 
                            /^\s+volume: / && indefault {printf $5; exit}'
}
getdefaultsinkmute() {
    pacmd list-sinks | awk '/^\s+name: /{indefault = $2 == "<'$(getdefaultsinkname)'>"} 
                            /^\s+muted: / && indefault {printf $2; exit}'
}

if [ -d "$HOME/.nvm" ]; then
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
fi


